// Code generated by my-plugin. DO NOT EDIT.

package example

import "github.com/common-nighthawk/go-figure"

func (req *HelloRequest) ShowMessages() string {
	var result string
	fontStyle := "doom"
	result += req.Name
	fig := figure.NewFigure(result, fontStyle, true)
	return fig.String()
}
func (req *HelloResponse) ShowMessages() string {
	var result string
	fontStyle := "doom"
	result += req.Message
	fig := figure.NewFigure(result, fontStyle, true)
	return fig.String()
}
