// Code generated by my-plugin. DO NOT EDIT.

package example

func (req *HelloRequest) ShowMessages() string {
	var result string
	result += req.Name
	return result
}
func (req *HelloResponse) ShowMessages() string {
	var result string
	result += req.Message
	return result
}
